<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">

    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            background-color: #f4f4f4;
        }
        .container {
            max-width: 1200px;
            margin: 0 auto;
            padding: 20px;
        }
        .header {
            text-align: center;
            padding: 50px 0;
        }
        .header h1 {
            font-size: 36px;
            margin-bottom: 10px;
        }
        .header p {
            font-size: 18px;
            color: #777;
        }
        .cta-button {
            display: inline-block;
            background-color: #007BFF;
            color: #fff;
            padding: 10px 20px;
            text-decoration: none;
            border-radius: 5px;
            font-size: 18px;
            margin-top: 20px;
        }
        .content {
            padding: 40px 0;
        }
        .footer {
            text-align: center;
            padding: 20px 0;
            background-color: #333;
            color: #fff;
        }
        .social-icons {
            margin-top: 20px;
        }
        .social-icons a {
            color: #fff;
            margin: 0 10px;
            font-size: 24px;
            text-decoration: none;
        }
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>Welcome to My Personal Branding</h1>
            <p>Mari Berkolaborasi Bersama Kami </p>
            <a href="https://www.kangjadi.com/" class="cta-button">Get Started</a>
        </div>
        <div class="content">
            <h2>Nama : </h2>
            <p>Dedi Mujahidin., S. Kom</p>
            <h2>Riwayat Organisasi : </h2>
            <p>Badan Eksekutif Mahasiswa UNIKAMA
                Presiden Mahasiswa
                2022-2023</p>
            <p>PMII UNIKAMA
                Ketua Rayon Tan Malaka
                2020-2021</p>
            <p>Himpunan Mahasiswa Program Studi Teknik Informatika
                Minat Bakat
                2020-2021</p>
            <p>Senat Mahasiswa Fakultas SAINTEK
                Sekretaris Umum
                2021-2022</p>
            <p>Unit Keegiatan Mahasiswa PENALARAN
                Ketua Inkubator Infokom
                2020-2023</p>
            <p>MENTERI DALAM NEGERI
                BEM Kabinet SIAP
                2019-2020</p>
            <h2>Pengalaman</h2>
            <p>MAGANG MBKM BERSERTIFIKAT
                Back End Developer di PT Citiasia Inc. (2020)</p>
            <p>STUDI INDEPENDENT MBKM
                Mastery Program Artificial Intellegence di
                PT Orbit Future Academy (2021)</p>
            <p>KOMISARIS PT KANG JADI TECHNOLOGY
                Founder & CEO (2023)</p>
            <p>PENDANAAN IWDM SAMBATERNAK
                Founder & CTO (2022)</p>
            <p>PENDANAAN PKM PI ASOI
                Alat Sortir Kedelai Berbasis Image
                Processing di Balitkabi Pakisaji (2022)</p>
            <p>PENDANAAN PM PI FERMENTASI
                Penerapan Teknologi Fermentasi Penvediaan
                Pakan Berkualitas dan Berkelaniutan Ternak
                Ruminansia di Desa Karangkates (2021)</p>
            <p>FINALIS PROGRAM BANK INDONESIA
                Finalis Yelp Progam Bank Indonesia SAMBATERNAK
                (2022)</p>
        </div>
    </div>
    <div class="footer">
        <div class="social-icons">
            <a href="https://www.linkedin.com/in/deddymujahidin/" target="_blank"><i class="fab fa-linkedin"></i></a>
            <a href="https://www.instagram.com/dedi.mujahidin/" target="_blank"><i class="fab fa-instagram"></i></a>
            <a href="https://www.tiktok.com/@kangjadi.com" target="_blank"><i class="fab fa-tiktok"></i></a>
            <a href="https://www.youtube.com/@kangjadi" target="_blank"><i class="fab fa-youtube"></i></a>
            <a href="https://twitter.com/Dedi_Mujahidin" target="_blank"><i class="fab fa-twitter"></i></a>
            <a href="https://web.facebook.com/dedi.mujahidin.56" target="_blank"><i class="fab fa-facebook"></i></a>
        </div>
    </div>
</body>
</html>
